# Generated by Django 2.0.3 on 2018-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_num', models.CharField(max_length=50)),
                ('package_type', models.CharField(max_length=100)),
                ('package_company', models.CharField(max_length=100)),
                ('company_logo', models.CharField(max_length=1000)),
            ],
        ),
    ]
